version: '3'

services:

  wazuh-agent:
    container_name: wazuh-agent
    uts: host
    command:
      - hostname
    image: rahulosp/wazuh-agent:4.7.0-1
    restart: unless-stopped
    environment:
      MANAGER_IP: 10.10.10.15
      MANAGER_PORT: 1514
      MANAGER_PROTOCOL: tcp
    volumes:
      - /:/rootfs:ro
      - /etc/os-release:/etc/os-release
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/syslog:/var/log/syslog
      - /var/log/dpkg.log:/var/log/dpkg.log
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/wazuh-agent-conf/ossec.conf:/var/ossec/etc/ossec.conf:ro
    network_mode: "host"
    #healthcheck:
     #test: "pg_isready --username=postgres && cat /proc/1/cmdline | grep -q '^postgres'"
     #timeout: 5s
     #retries: 20
